no_gestionnaire_homepage:
    path:     /
    defaults: { _controller: NOGestionnaireBundle:Default:index }
no_gestionnaire_suivi:
    path:     /suivi_projet/{id}
    defaults: { _controller: NOGestionnaireBundle:Suivi:suivi }
    requirements:
        id: \d+
no_gestionnaire_ajout:
    path:     /ajout_projet
    defaults: { _controller: NOGestionnaireBundle:Projet:ajoutProjet }
no_gestionnaire_admin:
    path:     /espace_admin
    defaults: { _controller: NOGestionnaireBundle:Admin:admin }
no_gestionnaire_ajout_taches:
    path:     /ajout_taches/{id}
    defaults: { _controller: NOGestionnaireBundle:Tache:ajoutTaches }
    requirements:
        id: \d+
no_gestionnaire_modification:
    path:     /modification_tache/{idTache}
    defaults: { _controller: NOGestionnaireBundle:Tache:modificationTache }
    requirements:
        idTache: \d+
no_gestionnaire_tarif:
    path:     /tarif/{id}
    defaults: { _controller: NOGestionnaireBundle:Tarif:ajoutTarif }
    requirements:
        id: \d+
no_gestionnaire_jours_vendus:
    path:     /jours_vendus/{idProjet}
    defaults: { _controller: NOGestionnaireBundle:FormJoursVendus:joursVendus }
    requirements:
        idProjet: \d+
no_gestionnaire_jours_vendus_add:
    path:     /jours_vendus/add/{tacheId}/{profilId}/{idProjet}
    defaults: { _controller: NOGestionnaireBundle:FormJoursVendus:createForm }
    requirements:
        tacheId: \d+
        profilId: \d+
        idProjet: \d+
no_gestionnaire_jours_vendus_edit:
    path:     /jours_vendus/edit/{idProjet}/{joursVendusId}
    defaults: { _controller: NOGestionnaireBundle:FormJoursVendus:joursVendusEdit }
    requirements:
        idProjet: \d+
        joursVendusId: \d+
no_gestionnaire_jours_vendus_create:
    path:     /jours_vendus/create/{idProjet}
    defaults: { _controller: NOGestionnaireBundle:FormJoursVendus:joursVendusCreate }
    requirements:
        idProjet: \d+
no_gestionnaire_affichage:
    path:     /affichage/{id}
    defaults: { _controller: NOGestionnaireBundle:Projet:affichage }
    requirements:
        id: \d+