no_gestionnaire_homepage:
    path:     /
    defaults: { _controller: NOGestionnaireBundle:Default:index }
no_gestionnaire_suivi:
    path:     /suivi_projet/{id}
    defaults: { _controller: NOGestionnaireBundle:Projet:suivi }
    requirements:
        id: \d+
no_gestionnaire_ajout:
    path:     /ajout_projet
    defaults: { _controller: NOGestionnaireBundle:Projet:ajout }
no_gestionnaire_modification:
    path:     /modification_projet/{idTache}
    defaults: { _controller: NOGestionnaireBundle:Projet:modification }
    requirements:
        idTache: \d+
no_gestionnaire_admin:
    path:     /espace_admin
    defaults: { _controller: NOGestionnaireBundle:Projet:admin }
no_gestionnaire_ajout_taches:
    path:     /ajout_taches/{id}
    defaults: { _controller: NOGestionnaireBundle:Projet:ajoutTaches }
no_gestionnaire_tarif:
    path:     /tarif/{id}
    defaults: { _controller: NOGestionnaireBundle:Projet:tarif }
no_gestionnaire_jours_vendus:
    path:     /jours_vendus/{idProjet}
    defaults: { _controller: NOGestionnaireBundle:Projet:joursVendus }
no_gestionnaire_jours_vendus_add:
    path:     /jours_vendus/add/{tacheId}/{profilId}/{idProjet}
    defaults: { _controller: NOGestionnaireBundle:Projet:createForm }
    requirements:
        tacheId: \d+
        profilId: \d+
        idProjet: \d+
no_gestionnaire_jours_vendus_edit:
    path:     /jours_vendus/edit/{idProjet}/{joursVendusId}
    defaults: { _controller: NOGestionnaireBundle:Projet:joursVendusEdit }
    requirements:
        idProjet: \d+
        joursVendusId: \d+
no_gestionnaire_jours_vendus_create:
    path:     /jours_vendus/create/{idProjet}
    defaults: { _controller: NOGestionnaireBundle:Projet:joursVendusCreate }
    requirements:
        idProjet: \d+