no_user:
    resource: "@NOUserBundle/Resources/config/routing.yml"
    prefix:   /

no_gestionnaire:
    resource: "@NOGestionnaireBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
   resource: "@FOSUserBundle/Resources/config/routing/all.xml"
