NO\GestionnaireBundle\Entity\Client:
  type: entity
  table: client
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    nomClient:
      type: string
      length: 255
      nullable: true
      column: nom_client
    
          