NO\GestionnaireBundle\Entity\Projet:
  type: entity
  table: projet
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    nomProjet:
      type: string
      length: 255
      nullable: true
      column: nom_projet
    dateDebut:
      type: date
      nullable: true
      column: date_debut
    dateFin:
      type: date
      nullable: true
      column: date_fin
  manyToMany:
    users:
      targetEntity: NO\GestionnaireBundle\Entity\User
      joinTable:
        name: usersToProjet
        joinColumns:
          projet_id:
            referencedColumnName: id
        inverseJoinColumns:
          user_id:
            referencedColumnName: id
  manyToOne:          
    clients:
      targetEntity: NO\GestionnaireBundle\Entity\Client
      joinColumn:
        name: client_id
        referencedColumnName: id
    poles:
      targetEntity: NO\GestionnaireBundle\Entity\Pole
      joinColumn:
        name: pole_id
        referencedColumnName: id
    typologies:
      targetEntity: NO\GestionnaireBundle\Entity\Typologie
      joinColumn:
        name: typologie_id
        referencedColumnName: id
          