NO\GestionnaireBundle\Entity\Tache:
  type: entity
  repositoryClass: NO\GestionnaireBundle\Repository\TacheRepository
  table: tache
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    nomTache:
      type: string
      length: 255
      nullable: true
      column: nom_tache
    niveau:
      type: integer
      nullable: true
      column: niveau
    ordre:
      type: integer
      nullable: true
      column: ordre
    joursRealises:
      type: decimal
      scale: 1
      nullable: true
      column: jours_réalisés
    raf:
      type: decimal
      scale: 1
      nullable: true
      column: raf
  manyToOne:
    projets:
      targetEntity: NO\GestionnaireBundle\Entity\Projet
      joinColumn:
        name: projet_id
        referencedColumnName: id
    tacheMeres:
      targetEntity: NO\GestionnaireBundle\Entity\Tache
      joinColumn:
        name: tache_mere_id
        referencedColumnName: id
          