NO\GestionnaireBundle\Entity\User:
  type: entity
  table: user
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    nomUser:
      type: string
      length: 255
      nullable: true
      column: nom_user
    password:
      type: string
      length: 255
      nullable: true
      column: password
  manyToOne:
    poles:
      targetEntity: NO\GestionnaireBundle\Entity\Pole
      joinColumn:
        name: pole_id
        referencedColumnName: id
  manyToMany:          
    roles:
      targetEntity: NO\GestionnaireBundle\Entity\Role
      joinTable:
        name: roleToUser
        joinColumns:
          user_id:
            referencedColumnName: id
        inverseJoinColumns:
          role_id:
            referencedColumnName: id
          
          