<?php

namespace NO\GestionnaireBundle\Repository;

/**
 * GrileTarifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrilleTarifRepository extends \Doctrine\ORM\EntityRepository
{
}