<?php

namespace NO\GestionnaireBundle\Repository;

/**
 * NbJourVendusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NbJourVendusRepository extends \Doctrine\ORM\EntityRepository
{
}