<?php

namespace NO\GestionnaireBundle\Repository;

/**
 * NbJourVendusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NbJourVendusRepository extends \Doctrine\ORM\EntityRepository
{
	public function sommeJoursVendus($idProjet)
	{
		$somme = $this->_em->createQueryBuilder()
							->select('ta')
							->from('NOGestionnaireBundle:Tache', 'ta')
							->where('ta.projet = :idProjet')
							->groupBy('ta.id')
							->orderBy('ta.niveau')
							->addOrderBy('ta.tacheMeres')
							->addOrderBy('ta.ordre')
							->setParameter('idProjet', $idProjet)
							->getQuery();
		return $somme->getResult();
	}

	public function sommeTotaleJoursVendus($idProjet){

		$somme = $this->createQueryBuilder('nb')
						->select('sum(nb.joursVendus) as somme')
						->leftJoin('nb.tache', 'ta')
						->where('ta.projet = :idProjet')
						->setParameter('idProjet', $idProjet)
						->getQuery();
		return $somme->getResult();
	}
}