<?php

namespace NO\GestionnaireBundle\Repository;

/**
 * NbJourVendusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NbJourVendusRepository extends \Doctrine\ORM\EntityRepository
{
	public function sommeJoursVendus($idProjet)
	{
		$somme = $this->_em->createQueryBuilder()
								->select('ta')
								->from('NOGestionnaireBundle:Tache', 'ta')
								->leftJoin('ta.joursVendus', 'nb')
								->addSelect('sum(nb.joursVendus) as somme')
								->where('ta.projet = :idProjet')
								->groupBy('ta.id')
								->orderBy('ta.ordre')
								->addOrderBy('ta.tacheMeres')
								->addOrderBy('ta.nomTache', 'ASC')
								->setParameter('idProjet', $idProjet)
								->getQuery();
		return $somme->getResult();
	}
}