<?php

namespace NO\GestionnaireBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * TacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TacheRepository extends \Doctrine\ORM\EntityRepository
{
	public function afficheTachesMeres($pattern)
	{
		return $this
			->createQueryBuilder('t')
			->where('t.niveau = :pattern')
			->setParameter('pattern', $pattern);
	}

	public function afficheTachesEnfant($enfant)
	{
		return $this
			->createQueryBuilder('te')
			->where('te.tacheMeres != :enfant')
			->setParameter('enfant', $enfant);
	}

	public function afficheToutesLesTaches($page, $nbParPage)
	{
		$query = $this->_em->createQueryBuilder()
					->select('ta')
					->from('NOGestionnaireBundle:Tache', 'ta')
					->where('ta.tacheMeres is not null')
					->getQuery()
					->setFirstResult(($page-1) * $nbParPage)
					->setMaxResults($nbParPage);

		return new Paginator($query, true);
	}
}
