<?php

namespace NO\GestionnaireBundle\Repository;

/**
 * TacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TacheRepository extends \Doctrine\ORM\EntityRepository
{
	public function afficheTachesMeres($pattern)
	{
		return $this
			->createQueryBuilder('t')
			->where('t.niveau = :pattern')
			->setParameter('pattern', $pattern);
	}

	public function afficheTachesEnfant($enfant)
	{
		return $this
			->createQueryBuilder('te')
			->where('te.tacheMeres != :enfant')
			->setParameter('enfant', $enfant);
	}
}
