<?php

namespace NO\GestionnaireBundle\Repository;

/**
 * TypologieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypologieRepository extends \Doctrine\ORM\EntityRepository
{
}
