<?php

namespace NO\GestionnaireBundle\Repository;

/**
 * UserFosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserFosRepository extends \Doctrine\ORM\EntityRepository
{
}
